### ISSUE TITLE
How to create dll unity? 

### ISSUE THREAD

**Issue by thienha1** [TiberiumN/nim-osureplay#1]
How ti create that without thousand error like ; > }{~

**Comment by TiberiumN** [comment]
Hi, you want to use my library from Unity?

**Comment by TiberiumN** [comment]
You can contact me from facebook/skype/discord, this isn't the best place for questions

**Comment by TiberiumN** [comment]
My facebook - https://www.facebook.com/tiberium1111

**Comment by thienha1** [comment]
Discord??

**Comment by TiberiumN** [comment]
@thienha1 yeah, Tiberium#3287

**Comment by thienha1** [comment]
I sent to you friend request and you are not respond to me!!!
